# Generated by Django 3.2.12 on 2022-03-29 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pastes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='The name of the paste')),
                ('text', models.TextField(verbose_name='Content of the paste')),
                ('expire_after', models.DateField(verbose_name="The paste's expiration time")),
                ('visibility', models.BooleanField(default=True, verbose_name='Visibility of the paste')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='username')),
            ],
        ),
    ]
