# Generated by Django 3.2.12 on 2022-03-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0002_auto_20220329_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='expire_after',
            field=models.TextField(verbose_name="The paste's expiration time"),
        ),
    ]
